api = "0.10"

[buildpack]
id = "heroku/php"
version = "0.2.0"
name = "Heroku PHP"
homepage = "https://github.com/heroku/buildpacks-php"
description = "Heroku's buildpack for PHP applications."
keywords = ["php", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

# Temporary workaround until Buildpacks GHAs get a release
# which includes Pack 0.34.0 or later:
# https://github.com/buildpacks/github-actions/releases
# https://github.com/buildpacks/pack/releases/tag/v0.34.0
# https://github.com/buildpacks/pack/pull/2081
[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets.distros]]
name = "ubuntu"
version = "20.04"

[[targets.distros]]
name = "ubuntu"
version = "22.04"

[[targets.distros]]
name = "ubuntu"
version = "24.04"

[[targets]]
os = "linux"
arch = "arm64"

[[targets.distros]]
name = "ubuntu"
version = "24.04"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-php" }
