api = "0.9"

[buildpack]
id = "heroku/php"
version = "0.1.2"
name = "Heroku PHP"
homepage = "https://github.com/heroku/buildpacks-php"
description = "Heroku's buildpack for PHP applications."
keywords = ["php", "heroku"]
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-php" }
