api = "0.10"

[buildpack]
id = "heroku/php"
version = "1.0.6"
name = "Heroku PHP"
homepage = "https://github.com/heroku/buildpacks-php"
description = "Heroku's buildpack for PHP applications."
keywords = ["php", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[targets]]
os = "linux"
arch = "amd64"

[[targets.distros]]
name = "ubuntu"
version = "22.04"

[[targets.distros]]
name = "ubuntu"
version = "24.04"

[[targets]]
os = "linux"
arch = "arm64"

[[targets.distros]]
name = "ubuntu"
version = "24.04"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-php" }
